version: '3.8'

services:
  sports_streaming:
    build: .
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"